### PR TITLE
Instant converter

### PR DESCRIPTION
**Pull request by JamesMcIntosh**
Hi,

Here is a pull request which adds a Joda Instant converter
Please let me know if you have any feedback to help get this included into the library.

Kind regards
James McIntosh

### CODE REVIEW

**Comment by JamesMcIntosh** [comment]
Is there any reason the work done on GautierLevert fork of the project hasn't been reincorporated back into the project as it covers may other Joda serialisations too?

https://github.com/GautierLevert/gson-jodatime-serialisers

**Comment by gkopff** [comment]
There was a PR #23, but it was unnecessarily invasive - the entire source was reformatted.

The Duration converter that was in the original PR was cherry picked and included.

**Comment by JamesMcIntosh** [comment]
Fair enough, thanks for bringing pulling in this request.

**Comment by gkopff** [comment]
In the coming days I'll prepare a release and publish it to Maven Central.

Is there anything else you would like to see get in before then?

**Comment by JamesMcIntosh** [comment]
I don't have anything else at the moment, many thanks.

**Comment by JamesMcIntosh** [comment]
Hi Greg,
Do you have an ETA for the release?
Kind regards
James

**Comment by gkopff** [comment]
Apologies James - life got busy.  I'll do it today.

**Comment by gkopff** [comment]
@JamesMcIntosh it's released.

**Pull request merged**
