### PR TITLE
Add Kotlin extension functions support

### LINKED ISSUE #47: Add Kotlin extension functions
This is a suggestion, it would be handy to have Kotlin extension functions for all `Converters.register*` functions.

For example, `Converters.registerDateTime(GsonBuilder)` would become:
```kotlin
fun GsonBuilder.registerDateTime(): GsonBuilder {
    registerTypeAdapter(DATE_TIME_TYPE, DateTimeConverter())
    return this
}
```

And consequentially, `Converters.registerDateTime(new GsonBuilder()).create();` would become:
```kotlin
GsonBuilder().registerDateTime().create()
```

### PR DESCRIPTION
**Pull request by mihakrajnc**
Added support for extension functions for the Converters class logic. Resolves #47

### CODE REVIEW

**Comment by mihakrajnc** [comment]
@gkopff Tested the jar from `mvn package` and the extension functions work properly. Can you please check the `pom.xml` file if everything is ok? I kept the configuration that IntelliJ applied and it seems to work.

**Comment by gkopff** [comment]
Thanks @mihakrajnc 

Let me know if you're interested in doing the same to the [java.time serialisers](https://github.com/gkopff/gson-javatime-serialisers) :-)

**Comment by gkopff** [comment]
I'll do a release once I've had time to adjust the README to spruik your good work.

**Comment by gkopff** [comment]
@mihakrajnc 1.8.0 has been released.

**Comment by gkopff** [comment]
@mihakrajnc Do you have some short examples of the Kotlin extension usage that can go into the README?

**Pull request merged**
