### PR TITLE
Update the InstantConverter to be able to deserialize more strings

### LINKED ISSUE #49: InstantConverter crashes on parsing dates that have no millisecond value
Parsing dates with no millisecond values breaks for instants.
E.g 2019-07-23T00:06:12Z

### PR DESCRIPTION
**Pull request by nathanrobb**
- Added support for strings with no milliseconds
- Added support for strings with milliseconds
- Added support for strings with time zone offsets
- Fixes #49

### CODE REVIEW

**Comment by gkopff** [comment]
Thanks @nathanrobb I'll look at it soon.

**Comment by gkopff** [comment]
I will put together a new release soon to incorporate these.  Do you have any other contributions before I do so?

**Comment by nathanrobb** [comment]
> Do you have any other contributions before I do so?

Probably not, no.

**Comment by gkopff** [comment]
Very good, thanks for this one :)

**Comment by gkopff** [comment]
@nathanrobb 1.8.0 has been released.

**Pull request merged**
